# Generated by Django 3.0.4 on 2020-04-08 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('rst', models.CharField(max_length=1200)),
                ('rst_attach', models.FileField(blank=True, null=True, upload_to='')),
                ('created_by', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_id', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1200)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('seen', models.BooleanField(default=0)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='inbox_members',
            fields=[
                ('inbox_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('people_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('created_by', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
                ('order_title', models.CharField(max_length=100)),
                ('order_pricing', models.IntegerField()),
                ('requirement', models.CharField(max_length=1000)),
                ('requirement_assets', models.FileField(blank=True, null=True, upload_to='')),
                ('delivery', models.BooleanField(default=0)),
                ('order_completed', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='p_service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('pricing', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1200)),
                ('pic_first', models.FileField(blank=True, null=True, upload_to='')),
                ('pic_second', models.FileField(blank=True, null=True, upload_to='')),
                ('pic_third', models.FileField(blank=True, null=True, upload_to='')),
                ('published_date', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='port_folio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('picture', models.FileField(null=True, upload_to='')),
                ('skills', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('degree', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=100)),
            ],
        ),
    ]
