# Generated by Django 3.0.4 on 2020-03-22 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p_service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('pricing', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1200)),
                ('pic_first', models.FileField(null=True, upload_to='')),
                ('pic_second', models.FileField(null=True, upload_to='')),
                ('pic_third', models.FileField(null=True, upload_to='')),
                ('published_date', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='port_folio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('picture', models.FileField(null=True, upload_to='')),
                ('skills', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('degree', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=100)),
            ],
        ),
    ]
