# Generated by Django 3.0.4 on 2020-04-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='direct_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_id', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1200)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('seen', models.BooleanField(default=0)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='inbox',
        ),
    ]
