# Generated by Django 3.0.4 on 2020-04-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0002_auto_20200408_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_service',
            name='delivery_time',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
