# Generated by Django 3.0.4 on 2020-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0003_p_service_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_service',
            name='delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
