# Generated by Django 3.0.4 on 2020-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0004_auto_20200323_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_completed',
            field=models.BooleanField(default=0),
        ),
    ]
