# Generated by Django 3.0.4 on 2020-03-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0005_auto_20200323_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
    ]
