# Generated by Django 3.0.4 on 2020-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0007_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_service',
            name='pic_first',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='p_service',
            name='pic_second',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='p_service',
            name='pic_third',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
