# Generated by Django 3.0.4 on 2020-03-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0009_order_chats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_chats',
        ),
    ]
