# Generated by Django 3.0.4 on 2020-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0011_chats_order_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_chat',
            name='chat',
        ),
        migrations.AddField(
            model_name='order_chat',
            name='created_by',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order_chat',
            name='text',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_chat',
            name='user',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_chat',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='chats',
        ),
    ]
