# Generated by Django 3.0.4 on 2020-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0012_auto_20200327_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='buyer',
        ),
        migrations.AddField(
            model_name='orders',
            name='seller',
            field=models.CharField(default='aarav', max_length=100),
            preserve_default=False,
        ),
    ]
