# Generated by Django 3.0.4 on 2020-03-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0014_buyer_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_request',
            name='user',
            field=models.CharField(default='p', max_length=100),
            preserve_default=False,
        ),
    ]
