# Generated by Django 3.0.4 on 2020-04-06 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_hire', '0018_auto_20200401_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='inbox',
            fields=[
                ('i_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1200)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='inbox_members',
            fields=[
                ('inbox_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('people_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
    ]
